### ISSUE TITLE
Добавьте Yaml Config Manager

### ISSUE THREAD

**Issue by Regeno** [qbaddev/UUC#6]
Есть несколько рекомендаций.

1) Сделайте что бы плагины были в виде папок
2) Уберите библиотеки - так как они уже не будут нужны
3) Сделайте yaml конфигурацию, папку plugins_conf

**Comment by qbaddev** [comment]
**Хорошо, есть еще предложения?**

**Comment by qbaddev** [comment]
Я подумаю над вашим соощением.
